language: csharp
solution: CheckSwpProject.sln
before_deploy:
- cd Testrunner.Console/bin/Release/
- zip -r SwpTestTool.zip .
- ls -l
deploy:
  provider: releases
  api_key:
    secure: ivZkuVFL0nHkx1fOOhIWiKBrJOhcUXSODgPYVOWj+B+Ka+uRmByK8nuVlBXza+fVb/GdBcjXGXm9TmlrMoD/XzGN2cgF58SbVGhk10gdg22tUs2lBXMKDY1fHmksy4S7oedj62CB+dfqdaSdNdLkvTj2vjYXE4bURff9JMp4ys3bxpjdho/aC/kf7ETvIaqTvVJT624jAoDO+V4/GQIyat/+lI5+gvFGymNo1ssrJ02swbBVDzooBwhZnfMewrNLyu28jjN5H87E/U6v59h/movJmji1Bh/W5MWoD/R8KwRwl66vnoeQFVDxz7kGJKykyNsQl7OBN/33RmgTzXKgNuajiq052h+iManj1t0LyqbPC6M8OGGvzMHGAxPju40OpFgI6pip5r0FQdLkXtN7n8T0IyTB1vC7/qtLjdPkbvnYCOpkPlLyR8r2BtZ6+/09fpP9laKZZgnarS1gy6in8w6RYrbGtnF2p95i54lXt+BnGPn5A69Ve0/j0yABCf4cV+Q4/Zxtcn+68Jx6xVLkHrowXGQ2RfoqXii2YzMjsPDovtd8495HEQr/weugUwkqRjmfHyXJnndzgUlMWnqT8sdlQoX5/sThLFwu6FQK4Pm2JDn0wXlDM/RtoZSEFNqQu45xVmQIY98Ntf/U4XOVkGT6Q+/QVvamZh5UEiT2gU0=
  file: SwpTestTool.zip
  on:
    repo: fhtw-swp-tutorium/dotNet-swp-test-tool
    tags: true